image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore /workspace/src/Build.sln
      dotnet build /workspace/src/NotBuild.sln      
vscode:
  extensions:
    - muhammad-sammy.csharp